---
- name: Create the backup directory
  file:
    path: "{{ backup_directory_remote }}"
    state: directory
    mode: 0755

- name: Create a backup of the node hosts
  archive:
    path:
      - /usr/lib/systemd/system/atomic-openshift-*.service
      - /etc/origin/node/node-config.yaml
    dest: "{{ backup_directory_remote }}/node_archive.tar.gz"

- name: Fetch archives
  fetch:
    src: "{{ backup_directory_remote }}/node_archive.tar.gz"
    dest: "{{ backup_directory_local }}"
